gems: [jekyll-paginate]
permalink   : /:year/:month/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: "Ryan Currie"
description: "Tech Enthusiast"
email: dddbliss@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://ryancurrie.me"
url: "http://ryancurrie.me/"
repository: "https://github.com/nandomoreirame/lora"
disqus_shortname: "ryancurrie"
google_analytics: UA-52446115-1

# social footer
social:
  github:
    slug: github
    link: http://github.com/dddbliss
  facebook:
    slug: facebook
    link: http://facebook.com/dddbliss
  twitter:
    slug: twitter
    link: http://twitter.com/dddbliss
